

- name: Install Nginx
  yum:
    name: "{{ nginx_package }}"
    state: present

- name: Start and Enable Nginx
  service:
    name: "{{ nginx_service }}"
    state: started
    enabled: yes

- name: Deploy Website Template
  template:
    src: index.html.j2
    dest: "{{ web_root }}/index.html"
  notify: restart nginx
